#!/bin/bash

echo "=================================================="
echo "  OzeanLive - Teensy 4.1 Aquarium Tamagotchi"
echo "=================================================="
echo ""
echo "⚠️  IMPORTANT NOTICE:"
echo ""
echo "This is an EMBEDDED SYSTEMS PROJECT for Teensy 4.1 hardware."
echo "It cannot run in the Replit cloud environment."
echo ""
echo "This project requires:"
echo "  • Teensy 4.1 microcontroller"
echo "  • ST7789 display (320x170px)"
echo "  • 3 physical buttons"
echo ""
echo "What you can do in Replit:"
echo "  ✓ Edit the C++ source code"
echo "  ✓ Review the project architecture"
echo "  ✓ Understand the game logic"
echo ""
echo "To build and upload to hardware:"
echo "  1. Install PlatformIO on your local machine"
echo "  2. Run: pio run --target upload"
echo ""
echo "Project files are ready for editing!"
echo "See replit.md for more information."
echo "=================================================="
